board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #url 요청 맨앞에 posts가 들어오면
    #위임한다
    path('posts/', include('post.urls')),
]

post/urls.py
from django.urls import path
from . import views  #app에서 만든 views

app_name = 'post'

urlpatterns=[
    path('', views.list, name='list'),
    path('create/', views.create, name='create'),
    path('<int:id>/detail/', views.detail, name='detail'),
    path('<int:id>/update', views.update, name = 'update'),
    path('<int:id>/delete', views.delete, name = 'delete'),
    ]

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50) #컬럼 두개 추가
    content = models.CharField(max_length=100)
    
    def __str__(self): #오브젝트 출력할때 타이틀로 출력하도록 재설정
        return self.title

post/forms.py
from django import forms

class PostForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'editable'}))
    
    
    

post/views.py
from django.shortcuts import render, redirect, resolve_url
from . import views
from .forms import PostForm
from .models import Post

# Create your views here.
def list(request):
    posts = Post.objects.all()
    return render(request, 'post/list.html',{'posts':posts})
    
def create(request):
    if request.method == 'POST':
        #저장로직
        form = PostForm(request.POST) # 입력했던 title, content가 request.POST안에 들어가있음
        if form.is_valid(): #규칙이 어긋나는지 검증하는 과정
            title = form.cleaned_data['title']
            # title = form.cleaned_data.get('title')
            content = form.cleaned_data['content']
            Post.objects.create(title=title, content=content)
        
            return redirect(resolve_url('post:list'))
        
        
    else:
        form = PostForm() #html코드로 바꿔주는애
    return render(request, 'post/create.html', {'form':form})


def detail(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'post/detail.html',{'post':post})
    
    
def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect(resolve_url('post:list'))
    
def update(request, id):
    post = Post.objects.get(id=id)
    if request.method =='POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            # post.update(title=title, content=content)
            post.save()
            return redirect(resolve_url('post:detail', id))
    
    else:
        form = PostForm({'title':post.title,'content':post.content})
        return render(request, 'post/update.html',{'form':form,'post':post})

post/templates/post/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
</head>
<body>
    <h1>base page</h1>
    <a href="{% url 'post:create' %}">작성</a>
    {% block body_block %}
    
    {% endblock %}
</body>
</html>

post/templates/post/create.html
{% extends 'post/base.html' %}


{%block body_block%}

<form action="{% url 'post:create' %}" method='POST'>
    {% csrf_token %}
    {{form}}
    <input type="submit"/>

</form>
<script>var editor = new MediumEditor('.editable');</script>

{% endblock%}

post/templates/post/detail.html
{% extends 'post/base.html' %}
{% block body_block %}

<a href="{% url 'post:delete' id=post.id %}">삭 제 </a>
<a href="{% url 'post:update' id=post.id %}">수 정 </a>
<h1>{{post.title}}</h1>
<h2>{{post.content|safe}}</h2>  


{% endblock %}

post/templates/post/list.html
{% extends 'post/base.html' %}

{%block body_block%}
<h1> list page< /h1>
{% for post in posts %}
    <h2>{{post.title}}</h2>
    <a href="{% url 'post:detail' id=post.id %}">detail</a>
{% endfor %}

{% endblock%}

post/templates/post/update.html
{% extends 'post/base.html' %}

{% block body_block %}

<form action="{% url 'post:update' id=post.id %}" method='POST'>
    {% csrf_token %}
    {{form}}
    <input type="submit"/>

</form>
<script>var editor = new MediumEditor('.editable');</script>


{% endblock %}